baseurl = "http://pouriya.org"

languageCode = "fa-IR"

title = "Erlang Farsi"

author = "Pouriya Jahanbakhsh"

canonifyurls = true

languagecode = "en"

theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

copyRight = "2019 © erlang-fa.ir"

googleAnalytics = ""


[params]
  desc = "ارلنگ يک زبان برنامه‌نویسی تابع‌گرا (Functional) برای توسعه برنامه‌های همروند (Concurrent)، توزیع شده (Distributed)، بی‌درنگ (Soft real-time) و بدون توقف (Non-stop) است که امکان تغییر کد های برنامه‌نویسی در زمان اجرا (Hot swapping) را نیز به ما میدهد."
  sitename = "Erlang"
  disableWebFonts = false
  siteGitURL = "https://github.com/pouriya-jahanbakhsh/erlang-fa.ir"
  twitter = "ErlangFarsi"


[[menu.main]]
    name = "DONATE"
    url  = "https://idpay.ir/codefather"

[[menu.main]]
    name = "Contribute"
    url  = "https://github.com/Pouriya-Jahanbakhsh/erlang-fa.ir"
